openapi: 3.0.0
info:
  title: Autenticação
  version: '1.0'
  contact:
    name: Carlos Tirabassi
    email: carlos@bitize.com.br
  description: API de integração com o backend do Bitize
servers:
  - url: 'https://api.bitize.com.br'
    description: Produção
  - url: 'https://api-tst.bitize.com.br'
    description: Testes
paths:
  /auth:
    get:
      summary: Autenticação - Refresh Token
      tags:
        - refresh token
        - login
        - auth
        - autenticação
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: Token de acesso
                  refresh_token:
                    type: string
                    description: Refresh token
                  expiration_access_token:
                    type: string
                    description: Data de expiração do token de acesso
                  expiration_refresh_token:
                    type: string
                    description: Data de expiração do refresh token
              examples:
                Exemplo de retorno:
                  value:
                    access_token: eyJhbGcFOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyApZCI6IjI1NGJjMGU4LWU5NTMtNDRkZS05ZTUELTI0YWNiYTM1MDAyZiIsImlhdCI6MTYBMTk1MjI1OSwiZXhwIjoxNjEyMDM4NjU5fQ.hQL7SANKEVjepTgoPaBk6h0vZLOdu4tnVC6BIa3gQO0
                    refresh_token: eyJhbGcAOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJAZCI6IjI1NGJjMGU4LWU5NTMtNDRkZS05ZTUDLTa0YWNiYTM1MDAyZiIsImlhdCI6MXYxMTk1MjI1OSwiZXhwIjoxNjEyMTI1MDU5fQ.KdCuLqxBFxNaXwHgfjmyWd8X6BTAcpbCoCuRcnRGBxg
                    expiration_access_token: '2021-01-30T20:30:59.058Z'
                    expiration_refresh_token: '2021-01-31T20:30:59.058Z'
      operationId: get-signin
      description: Endpoint para obtenção de um novo token através de um refresh token válido
      parameters:
        - schema:
            type: string
          in: query
          name: refresh_token
          description: Refresh token
          required: true
      security: []
    post:
      summary: Autenticação - Token
      operationId: post-signin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: Token de acesso
                  refresh_token:
                    type: string
                    description: Refresh token
                  expiration_access_token:
                    type: string
                    description: Data de expiração do token de acesso
                  expiration_refresh_token:
                    type: string
                    description: Data de expiração do refresh token
              examples:
                Exemplo de retorno:
                  value:
                    access_token: eyJhbGcFOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyApZCI6IjI1NGJjMGU4LWU5NTMtNDRkZS05ZTUELTI0YWNiYTM1MDAyZiIsImlhdCI6MTYBMTk1MjI1OSwiZXhwIjoxNjEyMDM4NjU5fQ.hQL7SANKEVjepTgoPaBk6h0vZLOdu4tnVC6BIa3gQO0
                    refresh_token: eyJhbGcAOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJAZCI6IjI1NGJjMGU4LWU5NTMtNDRkZS05ZTUDLTa0YWNiYTM1MDAyZiIsImlhdCI6MXYxMTk1MjI1OSwiZXhwIjoxNjEyMTI1MDU5fQ.KdCuLqxBFxNaXwHgfjmyWd8X6BTAcpbCoCuRcnRGBxg
                    expiration_access_token: '2021-01-30T20:30:59.058Z'
                    expiration_refresh_token: '2021-01-31T20:30:59.058Z'
      description: Endpoint para obtenção do token de acesso a API
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                consumer_key:
                  type: string
                  description: Chave de consumo do API
                  format: uuid
                secret_key:
                  type: string
                  description: Chave secreta de acesso a API
              required:
                - consumer_key
                - secret_key
            examples:
              Exemplo:
                value:
                  consumer_key: 15aa5a99-b27e-48ab-8076-7da9059337cb
                  secret_key: ExEmPlO1234@#$
        description: ''
      tags:
        - auth
        - login
        - autenticação
        - token
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          required: true
      security: []
    parameters: []
  /vendors:
    get:
      summary: Listar Fornecedores
      tags:
        - vendors
        - fornecedores
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  paging:
                    type: object
                    properties:
                      limit:
                        type: number
                      page:
                        type: number
                      pages:
                        type: number
                      total:
                        type: number
                  sort:
                    type: array
                    items:
                      type: object
                  available_filters:
                    type: array
                    items:
                      type: object
                  applied_filters:
                    type: object
                  data:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          minLength: 1
                        external_id: {}
                        active:
                          type: boolean
                        notes: {}
                        created_at:
                          type: string
                          minLength: 1
                        updated_at:
                          type: string
                          minLength: 1
                        deleted_at: {}
                        company_id:
                          type: string
                          minLength: 1
                        customer_id:
                          type: string
                          minLength: 1
                        company:
                          type: object
                          properties:
                            id:
                              type: string
                              minLength: 1
                            name:
                              type: string
                              minLength: 1
                            company_name:
                              type: string
                            external_id: {}
                            national_document:
                              type: string
                              minLength: 1
                            state_document: {}
                            municipal_document: {}
                            country_id:
                              type: string
                              minLength: 1
                            state_iso:
                              type: string
                              minLength: 1
                            active:
                              type: boolean
                            situation:
                              type: string
                              minLength: 1
                            situation_date:
                              type: string
                              minLength: 1
                            opening:
                              type: string
                              minLength: 1
                            portuguese_description: {}
                            english_description: {}
                            spanish_description: {}
                            keywords: {}
                            localizable:
                              type: boolean
                            homologation_level:
                              type: string
                              minLength: 1
                            main_activity_code:
                              type: string
                              minLength: 1
                            main_activity:
                              type: string
                              minLength: 1
                            date_special_situation:
                              type: string
                              minLength: 1
                            special_situation:
                              type: string
                            last_update:
                              type: string
                              minLength: 1
                            logo_id:
                              type: string
                              minLength: 1
                            status:
                              type: string
                              minLength: 1
                            person:
                              type: string
                              minLength: 1
                            created_at:
                              type: string
                              minLength: 1
                            updated_at:
                              type: string
                              minLength: 1
                            deleted_at: {}
                            addresses:
                              type: array
                              uniqueItems: true
                              minItems: 1
                              items:
                                type: object
                                properties:
                                  id:
                                    type: string
                                    minLength: 1
                                  external_id: {}
                                  type:
                                    type: string
                                    minLength: 1
                                  country_id:
                                    type: string
                                    minLength: 1
                                  postal_code:
                                    type: string
                                    minLength: 1
                                  state_iso:
                                    type: string
                                    minLength: 1
                                  city:
                                    type: string
                                    minLength: 1
                                  ibge:
                                    type: string
                                    minLength: 1
                                  neighborhood:
                                    type: string
                                    minLength: 1
                                  street:
                                    type: string
                                    minLength: 1
                                  number:
                                    type: string
                                    minLength: 1
                                  complement:
                                    type: string
                                  notes: {}
                                  created_at:
                                    type: string
                                    minLength: 1
                                  updated_at:
                                    type: string
                                    minLength: 1
                                  deleted_at: {}
                                  company_id:
                                    type: string
                                    minLength: 1
                                required:
                                  - id
                                  - type
                                  - country_id
                                  - postal_code
                                  - state_iso
                                  - city
                                  - ibge
                                  - neighborhood
                                  - street
                                  - number
                                  - complement
                                  - created_at
                                  - updated_at
                                  - company_id
                            contacts:
                              type: array
                              uniqueItems: true
                              minItems: 1
                              items:
                                type: object
                                properties:
                                  id:
                                    type: string
                                    minLength: 1
                                  external_id: {}
                                  type:
                                    type: string
                                    minLength: 1
                                  title:
                                    type: string
                                    minLength: 1
                                  country_area_code:
                                    type: string
                                    minLength: 1
                                  phone:
                                    type: string
                                    minLength: 1
                                  extension: {}
                                  email:
                                    type: string
                                    minLength: 1
                                  notes: {}
                                  created_at:
                                    type: string
                                    minLength: 1
                                  updated_at:
                                    type: string
                                    minLength: 1
                                  deleted_at: {}
                                  company_id:
                                    type: string
                                    minLength: 1
                                required:
                                  - id
                                  - type
                                  - title
                                  - country_area_code
                                  - phone
                                  - email
                                  - created_at
                                  - updated_at
                                  - company_id
      operationId: get-vendors
      description: Lista os fornecedores cadastrados
      security:
        - Access Token: []
    parameters: []
    post:
      summary: Cadastrar Fornecedor
      operationId: post-vendors-id
      responses:
        '200':
          description: OK
      description: Cadastro de fornecedores
      security:
        - Access Token: []
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                national_document:
                  type: string
                  minLength: 1
                country_id:
                  type: string
                  minLength: 1
              required:
                - national_document
                - country_id
      tags:
        - vendors
        - fornecedores
  '/vendors/{id}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: ID do Fornecedor
    get:
      summary: Fornecedor
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  id:
                    type: string
                    minLength: 1
                    format: uuid
                    description: ID do Fornecedor
                  external_id:
                    type: string
                    description: Identificação customizada do cadastro
                  active:
                    type: boolean
                    description: Registro ativo
                  notes:
                    type: string
                    description: Observações
                  created_at:
                    type: string
                    minLength: 1
                    description: Data do cadastro
                  updated_at:
                    type: string
                    minLength: 1
                    description: Data da atualização
                  deleted_at:
                    type: string
                    description: Data da exclusão
                  company_id:
                    type: string
                    minLength: 1
                    format: uuid
                    description: ID da Empresa
                  customer_id:
                    type: string
                    minLength: 1
                    format: uuid
                    description: ID do Cliente
                  company:
                    type: object
                    required:
                      - contacts
                    description: Dados da empresa no Bitize
                    properties:
                      name:
                        type: string
                        minLength: 1
                        description: Razão Social
                      company_name:
                        type: string
                        minLength: 1
                        description: Nome Fantasia
                      national_document:
                        type: string
                        minLength: 1
                        description: CNPJ
                      state_document:
                        type: string
                        description: Inscrição estadual
                      municipal_document:
                        type: string
                        description: Inscrição municipal
                      country_id:
                        type: string
                        minLength: 1
                        description: Código do país
                      state_iso:
                        type: string
                        minLength: 1
                        description: UF
                      active:
                        type: boolean
                        description: Empresa ativa na plataforma
                      situation:
                        type: string
                        minLength: 1
                        description: Situação na Sefaz
                      situation_date:
                        type: string
                        minLength: 1
                        description: Data da situação na Sefaz
                      opening:
                        type: string
                        minLength: 1
                        description: Data de abertura da empresa
                      portuguese_description:
                        type: string
                        description: Descrição da Empresa em português
                      english_description:
                        type: string
                        description: Descrição da Empresa em inglês
                      spanish_description:
                        type: string
                        description: Descrição da Empresa em espanhol
                      homologation_level:
                        type: string
                        minLength: 1
                        description: Nível de homologação na plataforma
                      main_activity_code:
                        type: string
                        minLength: 1
                        description: Código da atividade
                      main_activity:
                        type: string
                        minLength: 1
                        description: Atividade
                      date_special_situation:
                        type: string
                        minLength: 1
                        description: Data da situação especial na Sefaz
                      special_situation:
                        type: string
                        description: Situação especial
                      last_update:
                        type: string
                        minLength: 1
                        description: Última atualização na SEFAZ
                      status:
                        type: string
                        minLength: 1
                        description: Status na SEFAZ
                      person:
                        type: string
                        minLength: 1
                        description: Tipo de Pessoa
                        enum:
                          - 'L: Pessoa Jurídica'
                          - 'N: Pessoa Física'
                      created_at:
                        type: string
                        minLength: 1
                        description: Data do cadastro na plataforma
                      updated_at:
                        type: string
                        minLength: 1
                        description: Data da atualização na plataforma
                      deleted_at:
                        type: string
                        description: Data da exclusão na plataforma
                      addresses:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        description: Endereços
                        items:
                          type: object
                          description: Endereço
                          properties:
                            id:
                              type: string
                              minLength: 1
                            external_id: {}
                            type:
                              type: string
                              minLength: 1
                            country_id:
                              type: string
                              minLength: 1
                            postal_code:
                              type: string
                              minLength: 1
                            state_iso:
                              type: string
                              minLength: 1
                            city:
                              type: string
                              minLength: 1
                            ibge:
                              type: string
                              minLength: 1
                            neighborhood:
                              type: string
                              minLength: 1
                            street:
                              type: string
                              minLength: 1
                            number:
                              type: string
                              minLength: 1
                            complement:
                              type: string
                              minLength: 1
                            notes: {}
                            created_at:
                              type: string
                              minLength: 1
                            updated_at:
                              type: string
                              minLength: 1
                            deleted_at: {}
                            company_id:
                              type: string
                              minLength: 1
                          required:
                            - id
                            - type
                            - country_id
                            - postal_code
                            - state_iso
                            - city
                            - ibge
                            - neighborhood
                            - street
                            - number
                            - complement
                            - created_at
                            - updated_at
                            - company_id
                      contacts:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              minLength: 1
                            external_id: {}
                            type:
                              type: string
                              minLength: 1
                            title:
                              type: string
                              minLength: 1
                            country_area_code:
                              type: string
                              minLength: 1
                            phone:
                              type: string
                              minLength: 1
                            extension: {}
                            email:
                              type: string
                              minLength: 1
                            notes: {}
                            created_at:
                              type: string
                              minLength: 1
                            updated_at:
                              type: string
                              minLength: 1
                            deleted_at: {}
                            company_id:
                              type: string
                              minLength: 1
                          required:
                            - id
                            - type
                            - title
                            - country_area_code
                            - phone
                            - email
                            - created_at
                            - updated_at
                            - company_id
                      logo_id:
                        type: string
                        description: ID do logo
                        format: uuid
              examples:
                example-1:
                  value:
                    id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                    external_id: string
                    active: true
                    notes: string
                    created_at: string
                    updated_at: string
                    deleted_at: string
                    company_id: b2e6a1c3-1a5e-44ae-a8fd-81f76fd715cf
                    customer_id: 160c0c4b-9966-4dc1-a916-8407eb10d74e
                    company:
                      name: string
                      company_name: string
                      national_document: string
                      state_document: string
                      municipal_document: string
                      country_id: string
                      state_iso: string
                      active: true
                      situation: string
                      situation_date: string
                      opening: string
                      portuguese_description: string
                      english_description: string
                      spanish_description: string
                      homologation_level: string
                      main_activity_code: string
                      main_activity: string
                      date_special_situation: string
                      special_situation: string
                      last_update: string
                      status: string
                      person: 'L: Pessoa Jurídica'
                      created_at: string
                      updated_at: string
                      deleted_at: string
                      addresses:
                        - id: string
                          external_id: null
                          type: string
                          country_id: string
                          postal_code: string
                          state_iso: string
                          city: string
                          ibge: string
                          neighborhood: string
                          street: string
                          number: string
                          complement: string
                          notes: null
                          created_at: string
                          updated_at: string
                          deleted_at: null
                          company_id: string
                      contacts:
                        - id: string
                          external_id: null
                          type: string
                          title: string
                          country_area_code: string
                          phone: string
                          extension: null
                          email: string
                          notes: null
                          created_at: string
                          updated_at: string
                          deleted_at: null
                          company_id: string
                      logo_id: 1e12da27-d253-43f5-9f73-dd2101ceac0d
      operationId: get-vendors-id
      description: Retorna os dados do fornecedor
      security:
        - Access Token: []
components:
  schemas:
    CompanyAddress:
      description: Endereço da Empresa
      type: object
      x-examples:
        Exemplo:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          external_id: string
          type: string
          country_id: string
          postal_code: string
          state_iso: string
          city: string
          ibge: string
          neighborhood: string
          street: string
          number: string
          complement: string
          notes: string
          created_at: string
          updated_at: string
          deleted_at: string
          company_id: string
      properties:
        id:
          type: string
          minLength: 1
          format: uuid
          description: Id do endereço
          readOnly: true
        external_id:
          type: string
          description: Identificador customizado
        type:
          type: string
          minLength: 1
          description: Tipo de endereço
        country_id:
          type: string
          minLength: 1
          description: Código do País
        postal_code:
          type: string
          minLength: 1
          description: CEP
        state_iso:
          type: string
          minLength: 1
          description: UF
        city:
          type: string
          minLength: 1
          description: Cidade
        ibge:
          type: string
          minLength: 1
          description: Código IBGE
        neighborhood:
          type: string
          minLength: 1
          description: Bairro
        street:
          type: string
          minLength: 1
          description: Rua
        number:
          type: string
          minLength: 1
          description: Número
        complement:
          type: string
          minLength: 1
          description: Complemento
        notes:
          type: string
          description: Observação
        created_at:
          type: string
          minLength: 1
          description: Data do cadastro
          readOnly: true
        updated_at:
          type: string
          minLength: 1
          description: Data da atualização
          readOnly: true
        deleted_at:
          type: string
          minLength: 1
          description: Data da exclusão
          readOnly: true
        company_id:
          type: string
          minLength: 1
          description: ID da empresa
          format: uuid
      required:
        - type
        - country_id
        - postal_code
        - state_iso
        - city
        - neighborhood
        - street
        - number
        - company_id
      title: Company address
    CompanyContact:
      description: Contato da Empresa
      type: object
      properties:
        id:
          type: string
          minLength: 1
          format: uuid
          description: Id do contato
          readOnly: true
        external_id:
          type: string
          description: Identificador customizado
        type:
          type: string
          minLength: 1
          description: Tipo de contato
        title:
          type: string
          minLength: 1
          description: Título
        country_area_code:
          type: string
          minLength: 1
          description: DDI
        phone:
          type: string
          minLength: 1
          description: Telefone com DDD
        extension:
          type: string
          description: Ramal
        email:
          type: string
          minLength: 1
          description: E-mail
        notes:
          type: string
          description: Observações
        created_at:
          type: string
          minLength: 1
          description: Data do cadastro
          readOnly: true
        updated_at:
          type: string
          minLength: 1
          description: Data da atualização
          readOnly: true
        deleted_at:
          type: string
          minLength: 1
          description: Data da exclusão
          readOnly: true
        company_id:
          type: string
          minLength: 1
          format: uuid
          description: Id da empresa
      required:
        - type
        - title
        - email
        - company_id
      x-examples:
        Exemplo:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          external_id: string
          type: string
          title: string
          country_area_code: string
          phone: string
          extension: string
          email: string
          notes: string
          created_at: string
          updated_at: string
          deleted_at: string
          company_id: b2e6a1c3-1a5e-44ae-a8fd-81f76fd715cf
    CompanyDocument:
      title: Company Document
      type: object
      properties:
        id:
          type: string
      description: Documento da Empresa
    Company:
      description: ''
      type: object
      properties:
        id:
          type: string
          minLength: 1
          description: Id da Empresa
          readOnly: true
        name:
          type: string
          minLength: 1
        company_name:
          type: string
          minLength: 1
        external_id:
          type: string
        national_document:
          type: string
          minLength: 1
        state_document:
          type: string
        municipal_document:
          type: string
        country_id:
          type: string
          minLength: 1
        state_iso:
          type: string
          minLength: 1
        active:
          type: boolean
        situation:
          type: string
          minLength: 1
        situation_date:
          type: string
          minLength: 1
        opening:
          type: string
          minLength: 1
        portuguese_description:
          type: string
        english_description:
          type: string
        spanish_description:
          type: string
        keywords:
          type: array
          items:
            type: string
        localizable:
          type: boolean
        homologation_level:
          type: string
          minLength: 1
        main_activity_code:
          type: string
          minLength: 1
        main_activity:
          type: string
          minLength: 1
        date_special_situation:
          type: string
          minLength: 1
        special_situation:
          type: string
        last_update:
          type: string
          minLength: 1
        logo_id: {}
        status:
          type: string
          minLength: 1
        person:
          type: string
          minLength: 1
        created_at:
          type: string
          minLength: 1
          readOnly: true
        updated_at:
          type: string
          minLength: 1
          readOnly: true
        deleted_at:
          type: string
          minLength: 1
          readOnly: true
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/CompanyAddress'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/CompanyContact'
        documents:
          type: array
          items:
            $ref: '#/components/schemas/CompanyDocument'
      required:
        - name
        - company_name
        - national_document
        - country_id
        - state_iso
        - active
        - situation
        - situation_date
        - opening
        - localizable
        - homologation_level
        - main_activity_code
        - main_activity
        - date_special_situation
        - special_situation
        - last_update
        - status
        - person
  securitySchemes:
    Access Token:
      type: http
      scheme: bearer
  parameters:
    Content-Type:
      name: Content-Type
      in: query
      required: true
      schema:
        type: string
        default: application/json
      description: Content Type
    Sort:
      name: Sort
      in: query
      schema:
        type: string
        example: sort=id-asc
      description: Ordenação
tags:
  - name: auth
  - name: login
  - name: autenticação
  - name: token
  - name: refresh token
  - name: vendors
  - name: fornecedores
security:
  - Token: []
